trakt:
    client_id: 'xxxx'
    client_secret: 'xxxx'
    recent_days: 30

radarr:
    enabled: True
    address: 'x.x.x.x:7878'
    apikey: 'xxx'

sonarr:
    enabled: True
    address: 'x.x.x.x:8989'
    apikey: 'xxx'

medusa:
    enabled: True
    address: 'x.x.x.x:8081'
    username: 'xxx'
    password: 'xxx'
